export const cardItem = [
  {
    id: 1,
    iamge: "/images/card/one.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },
  {
    id: 2,
    iamge: "/images/card/two.png",
    todayUpdate: "Today",
    todayLikes: "132",
    todayComents: "51",
    dateUpdate: "5-08-2024",
    dateLikes: "67",
    dateComents: "22",
    uploadImage: "Image upload",
    uploadDate: "5-08-2024",
  },
  {
    id: 3,
    iamge: "/images/card/three.png",
    todayUpdate: "Today",
    todayLikes: "100",
    todayComents: "30",
    dateUpdate: "25-11-2024",
    dateLikes: "50",
    dateComents: "20",
    uploadImage: "Image upload",
    uploadDate: "25-11-2024",
  },
  {
    id: 4,
    iamge: "/images/card/one.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },
  {
    id: 5,
    iamge: "/images/card/five.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },
  {
    id: 6,
    iamge: "/images/card/six.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },
  {
    id: 7,
    iamge: "/images/card/seven.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },
  {
    id: 8,
    iamge: "/images/card/four.png",
    todayUpdate: "Today",
    todayLikes: "128",
    todayComents: "31",
    dateUpdate: "9-08-2025",
    dateLikes: "87",
    dateComents: "65",
    uploadImage: "Image upload",
    uploadDate: "11-04-2025",
  },

];
